name: Weekly Training

on:
  schedule:
    - cron: "0 7 * * 1"  # Tous les lundis 08:00 heure FR (7h UTC)
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.13"   # Mets ici ta version locale !

      - name: Install dependencies
        run: |
          pip install -r api/requirements.txt

      - name: Run training script
        run: python training/train.py

      - name: Commit updated artifacts
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add artifacts/
          git commit -m "Weekly retraining update" || echo "No changes"
          git push || echo "No changes to push"